# Generated by Django 4.2.2 on 2023-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('published', 'Published')], default='processing', max_length=20),
        ),
    ]
