# Generated by Django 4.2.2 on 2023-06-06 10:14

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Another', 'Another'), ('Toyota', 'Toyota'), ('Mercedes', 'Mercedes'), ('BMW', 'Bmw'), ('Audi', 'Audi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Another', 'Another'), ('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('BK', 'Black'), ('WH', 'White'), ('SV', 'Silver'), ('GR', 'Gray')], max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=product.models.get_default_image, upload_to='cars'),
        ),
    ]
