# Generated by Django 4.2.2 on 2023-06-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_car_description_car_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
    ]
