# Generated by Django 4.2.2 on 2023-06-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_car_description_remove_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(default='Untitled', max_length=20),
        ),
    ]
