# Generated by Django 4.2.2 on 2023-06-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_reviews', '0001_initial'),
        ('product', '0008_car_description_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_reviews.comment'),
            preserve_default=False,
        ),
    ]
