# Generated by Django 4.2.2 on 2023-06-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='comment',
        ),
    ]
