# Generated by Django 4.2.1 on 2023-06-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_balance_total_balance_alter_balance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='product',
            field=models.IntegerField(),
        ),
    ]
